### ISSUE TITLE
做dota2地图遇到一个问题，求助大佬！

### ISSUE THREAD

**Issue by shenguanjiejie** [XavierCHN/Dota-Reborn-Code#7]
系统lua环境5.35
我单独创建了一个hello.lua文件,可以正常使用os.lua模块访问os.time()方法
但是我的dota2项目却找不到os.lua并报错, 我感觉是dota2的项目lua环境配置和系统的不同,但是又不知道该怎么解决这个问题.
这是我hello.lua
![Snipaste_2020-02-11_21-53-31](https://user-images.githubusercontent.com/9425605/74247251-bfc6f200-4d20-11ea-8345-a2d0106547bd.png)
这是我dota2项目的报错打印
![Snipaste_2020-02-11_21-50-26](https://user-images.githubusercontent.com/9425605/74247282-c7869680-4d20-11ea-903e-b99c933f01e9.png)

如果方便的话, 有没有相关qq或微信群可以拉我进去的? 或者能加你qq或微信好友最好了, 我微信号shenguanjiejie, 感激不尽.

**Comment by XavierCHN** [comment]
dota2删掉了os库
